services:
  rstudio:
    # image: timotheebacri/rstudio:latest-amd64
    image: timotheebacri/rstudio:latest-arm64
    container_name: rstudio
    # environment:
      # Default user is rstudio
      # USER: rstudio

      # rstudio's default password is rstudio
      # PASSWORD: rstudio

      # rstudio's default IDs are 1000:1000
      # USERID: 1000
      # GROUPID: 1000

      # Root account is disabled by default
      # ROOT: false # false,true

      # Default umask is 022
      # UMASK: # ${UMASK:=022}

      # By default, authentication is mandatory
      # DISABLE_AUTH: false # false,true

      # By default, shiny is not available
      # https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/add_shiny.sh
      # ADD: none # none,shiny

    # Docker uses its own user ID to create files, so avoid mounting /home in read-write
    volumes:
      # Make user host home folders available in read-only to avoid screwing up folder ownership
      #- /home/<user>:/host_home/<user>ro # Linux
      
      # The user running the container should avoid mounting the same folder many times or it may crash Docker
      - /Users/trfb201/docker/RStudio/home:/host_home/trfb201:ro
      
      # The user running Docker cannot share the Docker folders in their home directory in read-only as it will crash Docker
      # - /Users/dw356/available_to_rstudio_server:/host_home/dw356:ro
      
      - /Users/ik354:/host_home/ik354:ro
      - /Users/mh1176:/host_home/mh1176:ro
      - /Users/jm622:/host_home/jm622:ro
      - /Users/mcm216:/host_home/mcm216:ro
      # Everyone can access shared in principle
      - /Users/Shared:/host_home/Shared:ro
      
      # Local folder for /home, Docker will manage permission and ownership on its own
      - /Users/trfb201/docker/RStudio/container_home:/home

      # Store new user passwords
      - rstudio_etc:/etc
    ports:
      - 8787:8787
volumes:
  - rstudio_etc
